### ISSUE TITLE
Problem with `starts-with` and `ends-with`

### ISSUE THREAD

**Issue by timenz** [adxsoft/logseq-query-builder-plugin#5]
Hai @adxsoft , thanks for your cool plugin. I found something that I think its an issue.

When I generate this code, to search block with a starting text

```yaml
title: Example Commands
- blocks
    - startingtext*
```

The generated query is to search block with a ending text

```clojure
#+BEGIN_QUERY
{
:title [:b "Example Commands"]
:query [:find (pull ?block [*])
:where
[?block :block/content ?blockcontent]
[?block :block/page ?page]
[?page :block/name ?pagename]
[(clojure.string/ends-with? ?blockcontent "startingtext")]
]
}
#+END_QUERY
```

Likewise for the code to search block with a ending text.

**Comment by adxsoft** [comment]
Unfortunately starts-with? and ends-with? clojure functions are not working in Logseq its a known bug but has not yet been acted upon by the dev team. See https://github.com/logseq/logseq/discussions/8076. I will fix the problem you raised once the Logseq team fix the 8076 bug.

**Comment by adxsoft** [comment]
Thanks for raising this issue. The bug has been fixed so please update your plugin to version 0.81 by clicking 'Check Update' for the plugin in your Plugins menu and let me know if I can close the issue.
Thanks

**Comment by timenz** [comment]
Hi @adxsoft I already test it and its work as expected, thanks.

**Comment by adxsoft** [comment]
Thanks for the confirmation. Happy querying 😊

**Comment by adxsoft** [comment]
Closed issue
