### ISSUE TITLE
Unable to use `tab` as Indentation

### ISSUE THREAD

**Issue by timenz** [adxsoft/logseq-query-builder-plugin#6]
Hi @adxsoft , this is my second post as review for this plugin.

The issue is, if I use `tab` as indentation the line code is not processed, current workaround is I should use `space` twice for 1 level indentation.

This is the example using tab:

```
title: Example Commands
- blocks
[tab]- *endingtext
```

Result:

```clojure
#+BEGIN_QUERY
{
:title [:b "Example Commands"]
:query [:find (pull ?block [*])
:where
[?block :block/content ?blockcontent]
[?block :block/page ?page]
[?page :block/name ?pagename]
]
}
#+END_QUERY
```

Using space:

```
title: Example Commands
- blocks
[space][space]- *endingtext
```

Result:

```clojure
#+BEGIN_QUERY
{
:title [:b "Example Commands"]
:query [:find (pull ?block [*])
:where
[?block :block/content ?blockcontent]
[?block :block/page ?page]
[?page :block/name ?pagename]
[(clojure.string/starts-with? ?blockcontent "endingtext")]
]
}
#+END_QUERY
```

Thanks.

**Comment by adxsoft** [comment]
As this code also supports the web site at https://adxsoft.github.io/logseqadvancedquerybuilder/ the use of tabs for indentation of the simple commands is not possible. So for consistency between the online tool and the plugin you can use any number of leading spaces but the indentations must be consistent. I would suggest either two or four spaces is a good indentation value.
